/*
IMDb-API

The IMDb-API Documentation. You need a <a href='/Identity/Account/Manage' target='_blank'><code>API Key</code></a> for testing APIs.<br/><a class='link' href='/API'>Back to API Tester</a>

API version: 1.8.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// ActorShort struct for ActorShort
type ActorShort struct {
	Id NullableString `json:"id,omitempty"`
	Image NullableString `json:"image,omitempty"`
	Name NullableString `json:"name,omitempty"`
	AsCharacter NullableString `json:"asCharacter,omitempty"`
}

// NewActorShort instantiates a new ActorShort object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewActorShort() *ActorShort {
	this := ActorShort{}
	return &this
}

// NewActorShortWithDefaults instantiates a new ActorShort object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewActorShortWithDefaults() *ActorShort {
	this := ActorShort{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ActorShort) GetId() string {
	if o == nil || o.Id.Get() == nil {
		var ret string
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ActorShort) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *ActorShort) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableString and assigns it to the Id field.
func (o *ActorShort) SetId(v string) {
	o.Id.Set(&v)
}
// SetIdNil sets the value for Id to be an explicit nil
func (o *ActorShort) SetIdNil() {
	o.Id.Set(nil)
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *ActorShort) UnsetId() {
	o.Id.Unset()
}

// GetImage returns the Image field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ActorShort) GetImage() string {
	if o == nil || o.Image.Get() == nil {
		var ret string
		return ret
	}
	return *o.Image.Get()
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ActorShort) GetImageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Image.Get(), o.Image.IsSet()
}

// HasImage returns a boolean if a field has been set.
func (o *ActorShort) HasImage() bool {
	if o != nil && o.Image.IsSet() {
		return true
	}

	return false
}

// SetImage gets a reference to the given NullableString and assigns it to the Image field.
func (o *ActorShort) SetImage(v string) {
	o.Image.Set(&v)
}
// SetImageNil sets the value for Image to be an explicit nil
func (o *ActorShort) SetImageNil() {
	o.Image.Set(nil)
}

// UnsetImage ensures that no value is present for Image, not even an explicit nil
func (o *ActorShort) UnsetImage() {
	o.Image.Unset()
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ActorShort) GetName() string {
	if o == nil || o.Name.Get() == nil {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ActorShort) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *ActorShort) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *ActorShort) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *ActorShort) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *ActorShort) UnsetName() {
	o.Name.Unset()
}

// GetAsCharacter returns the AsCharacter field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ActorShort) GetAsCharacter() string {
	if o == nil || o.AsCharacter.Get() == nil {
		var ret string
		return ret
	}
	return *o.AsCharacter.Get()
}

// GetAsCharacterOk returns a tuple with the AsCharacter field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ActorShort) GetAsCharacterOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AsCharacter.Get(), o.AsCharacter.IsSet()
}

// HasAsCharacter returns a boolean if a field has been set.
func (o *ActorShort) HasAsCharacter() bool {
	if o != nil && o.AsCharacter.IsSet() {
		return true
	}

	return false
}

// SetAsCharacter gets a reference to the given NullableString and assigns it to the AsCharacter field.
func (o *ActorShort) SetAsCharacter(v string) {
	o.AsCharacter.Set(&v)
}
// SetAsCharacterNil sets the value for AsCharacter to be an explicit nil
func (o *ActorShort) SetAsCharacterNil() {
	o.AsCharacter.Set(nil)
}

// UnsetAsCharacter ensures that no value is present for AsCharacter, not even an explicit nil
func (o *ActorShort) UnsetAsCharacter() {
	o.AsCharacter.Unset()
}

func (o ActorShort) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id.IsSet() {
		toSerialize["id"] = o.Id.Get()
	}
	if o.Image.IsSet() {
		toSerialize["image"] = o.Image.Get()
	}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.AsCharacter.IsSet() {
		toSerialize["asCharacter"] = o.AsCharacter.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableActorShort struct {
	value *ActorShort
	isSet bool
}

func (v NullableActorShort) Get() *ActorShort {
	return v.value
}

func (v *NullableActorShort) Set(val *ActorShort) {
	v.value = val
	v.isSet = true
}

func (v NullableActorShort) IsSet() bool {
	return v.isSet
}

func (v *NullableActorShort) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableActorShort(val *ActorShort) *NullableActorShort {
	return &NullableActorShort{value: val, isSet: true}
}

func (v NullableActorShort) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableActorShort) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


