/*
IMDb-API

The IMDb-API Documentation. You need a <a href='/Identity/Account/Manage' target='_blank'><code>API Key</code></a> for testing APIs.<br/><a class='link' href='/API'>Back to API Tester</a>

API version: 1.8.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// Top250DataDetail struct for Top250DataDetail
type Top250DataDetail struct {
	Id NullableString `json:"id,omitempty"`
	Rank NullableString `json:"rank,omitempty"`
	Title NullableString `json:"title,omitempty"`
	FullTitle NullableString `json:"fullTitle,omitempty"`
	Year NullableString `json:"year,omitempty"`
	Image NullableString `json:"image,omitempty"`
	Crew NullableString `json:"crew,omitempty"`
	ImDbRating NullableString `json:"imDbRating,omitempty"`
	ImDbRatingCount NullableString `json:"imDbRatingCount,omitempty"`
}

// NewTop250DataDetail instantiates a new Top250DataDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTop250DataDetail() *Top250DataDetail {
	this := Top250DataDetail{}
	return &this
}

// NewTop250DataDetailWithDefaults instantiates a new Top250DataDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTop250DataDetailWithDefaults() *Top250DataDetail {
	this := Top250DataDetail{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Top250DataDetail) GetId() string {
	if o == nil || o.Id.Get() == nil {
		var ret string
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Top250DataDetail) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *Top250DataDetail) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableString and assigns it to the Id field.
func (o *Top250DataDetail) SetId(v string) {
	o.Id.Set(&v)
}
// SetIdNil sets the value for Id to be an explicit nil
func (o *Top250DataDetail) SetIdNil() {
	o.Id.Set(nil)
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *Top250DataDetail) UnsetId() {
	o.Id.Unset()
}

// GetRank returns the Rank field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Top250DataDetail) GetRank() string {
	if o == nil || o.Rank.Get() == nil {
		var ret string
		return ret
	}
	return *o.Rank.Get()
}

// GetRankOk returns a tuple with the Rank field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Top250DataDetail) GetRankOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Rank.Get(), o.Rank.IsSet()
}

// HasRank returns a boolean if a field has been set.
func (o *Top250DataDetail) HasRank() bool {
	if o != nil && o.Rank.IsSet() {
		return true
	}

	return false
}

// SetRank gets a reference to the given NullableString and assigns it to the Rank field.
func (o *Top250DataDetail) SetRank(v string) {
	o.Rank.Set(&v)
}
// SetRankNil sets the value for Rank to be an explicit nil
func (o *Top250DataDetail) SetRankNil() {
	o.Rank.Set(nil)
}

// UnsetRank ensures that no value is present for Rank, not even an explicit nil
func (o *Top250DataDetail) UnsetRank() {
	o.Rank.Unset()
}

// GetTitle returns the Title field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Top250DataDetail) GetTitle() string {
	if o == nil || o.Title.Get() == nil {
		var ret string
		return ret
	}
	return *o.Title.Get()
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Top250DataDetail) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Title.Get(), o.Title.IsSet()
}

// HasTitle returns a boolean if a field has been set.
func (o *Top250DataDetail) HasTitle() bool {
	if o != nil && o.Title.IsSet() {
		return true
	}

	return false
}

// SetTitle gets a reference to the given NullableString and assigns it to the Title field.
func (o *Top250DataDetail) SetTitle(v string) {
	o.Title.Set(&v)
}
// SetTitleNil sets the value for Title to be an explicit nil
func (o *Top250DataDetail) SetTitleNil() {
	o.Title.Set(nil)
}

// UnsetTitle ensures that no value is present for Title, not even an explicit nil
func (o *Top250DataDetail) UnsetTitle() {
	o.Title.Unset()
}

// GetFullTitle returns the FullTitle field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Top250DataDetail) GetFullTitle() string {
	if o == nil || o.FullTitle.Get() == nil {
		var ret string
		return ret
	}
	return *o.FullTitle.Get()
}

// GetFullTitleOk returns a tuple with the FullTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Top250DataDetail) GetFullTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.FullTitle.Get(), o.FullTitle.IsSet()
}

// HasFullTitle returns a boolean if a field has been set.
func (o *Top250DataDetail) HasFullTitle() bool {
	if o != nil && o.FullTitle.IsSet() {
		return true
	}

	return false
}

// SetFullTitle gets a reference to the given NullableString and assigns it to the FullTitle field.
func (o *Top250DataDetail) SetFullTitle(v string) {
	o.FullTitle.Set(&v)
}
// SetFullTitleNil sets the value for FullTitle to be an explicit nil
func (o *Top250DataDetail) SetFullTitleNil() {
	o.FullTitle.Set(nil)
}

// UnsetFullTitle ensures that no value is present for FullTitle, not even an explicit nil
func (o *Top250DataDetail) UnsetFullTitle() {
	o.FullTitle.Unset()
}

// GetYear returns the Year field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Top250DataDetail) GetYear() string {
	if o == nil || o.Year.Get() == nil {
		var ret string
		return ret
	}
	return *o.Year.Get()
}

// GetYearOk returns a tuple with the Year field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Top250DataDetail) GetYearOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Year.Get(), o.Year.IsSet()
}

// HasYear returns a boolean if a field has been set.
func (o *Top250DataDetail) HasYear() bool {
	if o != nil && o.Year.IsSet() {
		return true
	}

	return false
}

// SetYear gets a reference to the given NullableString and assigns it to the Year field.
func (o *Top250DataDetail) SetYear(v string) {
	o.Year.Set(&v)
}
// SetYearNil sets the value for Year to be an explicit nil
func (o *Top250DataDetail) SetYearNil() {
	o.Year.Set(nil)
}

// UnsetYear ensures that no value is present for Year, not even an explicit nil
func (o *Top250DataDetail) UnsetYear() {
	o.Year.Unset()
}

// GetImage returns the Image field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Top250DataDetail) GetImage() string {
	if o == nil || o.Image.Get() == nil {
		var ret string
		return ret
	}
	return *o.Image.Get()
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Top250DataDetail) GetImageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Image.Get(), o.Image.IsSet()
}

// HasImage returns a boolean if a field has been set.
func (o *Top250DataDetail) HasImage() bool {
	if o != nil && o.Image.IsSet() {
		return true
	}

	return false
}

// SetImage gets a reference to the given NullableString and assigns it to the Image field.
func (o *Top250DataDetail) SetImage(v string) {
	o.Image.Set(&v)
}
// SetImageNil sets the value for Image to be an explicit nil
func (o *Top250DataDetail) SetImageNil() {
	o.Image.Set(nil)
}

// UnsetImage ensures that no value is present for Image, not even an explicit nil
func (o *Top250DataDetail) UnsetImage() {
	o.Image.Unset()
}

// GetCrew returns the Crew field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Top250DataDetail) GetCrew() string {
	if o == nil || o.Crew.Get() == nil {
		var ret string
		return ret
	}
	return *o.Crew.Get()
}

// GetCrewOk returns a tuple with the Crew field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Top250DataDetail) GetCrewOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Crew.Get(), o.Crew.IsSet()
}

// HasCrew returns a boolean if a field has been set.
func (o *Top250DataDetail) HasCrew() bool {
	if o != nil && o.Crew.IsSet() {
		return true
	}

	return false
}

// SetCrew gets a reference to the given NullableString and assigns it to the Crew field.
func (o *Top250DataDetail) SetCrew(v string) {
	o.Crew.Set(&v)
}
// SetCrewNil sets the value for Crew to be an explicit nil
func (o *Top250DataDetail) SetCrewNil() {
	o.Crew.Set(nil)
}

// UnsetCrew ensures that no value is present for Crew, not even an explicit nil
func (o *Top250DataDetail) UnsetCrew() {
	o.Crew.Unset()
}

// GetImDbRating returns the ImDbRating field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Top250DataDetail) GetImDbRating() string {
	if o == nil || o.ImDbRating.Get() == nil {
		var ret string
		return ret
	}
	return *o.ImDbRating.Get()
}

// GetImDbRatingOk returns a tuple with the ImDbRating field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Top250DataDetail) GetImDbRatingOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ImDbRating.Get(), o.ImDbRating.IsSet()
}

// HasImDbRating returns a boolean if a field has been set.
func (o *Top250DataDetail) HasImDbRating() bool {
	if o != nil && o.ImDbRating.IsSet() {
		return true
	}

	return false
}

// SetImDbRating gets a reference to the given NullableString and assigns it to the ImDbRating field.
func (o *Top250DataDetail) SetImDbRating(v string) {
	o.ImDbRating.Set(&v)
}
// SetImDbRatingNil sets the value for ImDbRating to be an explicit nil
func (o *Top250DataDetail) SetImDbRatingNil() {
	o.ImDbRating.Set(nil)
}

// UnsetImDbRating ensures that no value is present for ImDbRating, not even an explicit nil
func (o *Top250DataDetail) UnsetImDbRating() {
	o.ImDbRating.Unset()
}

// GetImDbRatingCount returns the ImDbRatingCount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Top250DataDetail) GetImDbRatingCount() string {
	if o == nil || o.ImDbRatingCount.Get() == nil {
		var ret string
		return ret
	}
	return *o.ImDbRatingCount.Get()
}

// GetImDbRatingCountOk returns a tuple with the ImDbRatingCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Top250DataDetail) GetImDbRatingCountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ImDbRatingCount.Get(), o.ImDbRatingCount.IsSet()
}

// HasImDbRatingCount returns a boolean if a field has been set.
func (o *Top250DataDetail) HasImDbRatingCount() bool {
	if o != nil && o.ImDbRatingCount.IsSet() {
		return true
	}

	return false
}

// SetImDbRatingCount gets a reference to the given NullableString and assigns it to the ImDbRatingCount field.
func (o *Top250DataDetail) SetImDbRatingCount(v string) {
	o.ImDbRatingCount.Set(&v)
}
// SetImDbRatingCountNil sets the value for ImDbRatingCount to be an explicit nil
func (o *Top250DataDetail) SetImDbRatingCountNil() {
	o.ImDbRatingCount.Set(nil)
}

// UnsetImDbRatingCount ensures that no value is present for ImDbRatingCount, not even an explicit nil
func (o *Top250DataDetail) UnsetImDbRatingCount() {
	o.ImDbRatingCount.Unset()
}

func (o Top250DataDetail) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id.IsSet() {
		toSerialize["id"] = o.Id.Get()
	}
	if o.Rank.IsSet() {
		toSerialize["rank"] = o.Rank.Get()
	}
	if o.Title.IsSet() {
		toSerialize["title"] = o.Title.Get()
	}
	if o.FullTitle.IsSet() {
		toSerialize["fullTitle"] = o.FullTitle.Get()
	}
	if o.Year.IsSet() {
		toSerialize["year"] = o.Year.Get()
	}
	if o.Image.IsSet() {
		toSerialize["image"] = o.Image.Get()
	}
	if o.Crew.IsSet() {
		toSerialize["crew"] = o.Crew.Get()
	}
	if o.ImDbRating.IsSet() {
		toSerialize["imDbRating"] = o.ImDbRating.Get()
	}
	if o.ImDbRatingCount.IsSet() {
		toSerialize["imDbRatingCount"] = o.ImDbRatingCount.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableTop250DataDetail struct {
	value *Top250DataDetail
	isSet bool
}

func (v NullableTop250DataDetail) Get() *Top250DataDetail {
	return v.value
}

func (v *NullableTop250DataDetail) Set(val *Top250DataDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableTop250DataDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableTop250DataDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTop250DataDetail(val *Top250DataDetail) *NullableTop250DataDetail {
	return &NullableTop250DataDetail{value: val, isSet: true}
}

func (v NullableTop250DataDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTop250DataDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


