/*
IMDb-API

The IMDb-API Documentation. You need a <a href='/Identity/Account/Manage' target='_blank'><code>API Key</code></a> for testing APIs.<br/><a class='link' href='/API'>Back to API Tester</a>

API version: 1.8.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// WikipediaDataPlot struct for WikipediaDataPlot
type WikipediaDataPlot struct {
	PlainText NullableString `json:"plainText,omitempty"`
	Html NullableString `json:"html,omitempty"`
}

// NewWikipediaDataPlot instantiates a new WikipediaDataPlot object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWikipediaDataPlot() *WikipediaDataPlot {
	this := WikipediaDataPlot{}
	return &this
}

// NewWikipediaDataPlotWithDefaults instantiates a new WikipediaDataPlot object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWikipediaDataPlotWithDefaults() *WikipediaDataPlot {
	this := WikipediaDataPlot{}
	return &this
}

// GetPlainText returns the PlainText field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WikipediaDataPlot) GetPlainText() string {
	if o == nil || o.PlainText.Get() == nil {
		var ret string
		return ret
	}
	return *o.PlainText.Get()
}

// GetPlainTextOk returns a tuple with the PlainText field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WikipediaDataPlot) GetPlainTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PlainText.Get(), o.PlainText.IsSet()
}

// HasPlainText returns a boolean if a field has been set.
func (o *WikipediaDataPlot) HasPlainText() bool {
	if o != nil && o.PlainText.IsSet() {
		return true
	}

	return false
}

// SetPlainText gets a reference to the given NullableString and assigns it to the PlainText field.
func (o *WikipediaDataPlot) SetPlainText(v string) {
	o.PlainText.Set(&v)
}
// SetPlainTextNil sets the value for PlainText to be an explicit nil
func (o *WikipediaDataPlot) SetPlainTextNil() {
	o.PlainText.Set(nil)
}

// UnsetPlainText ensures that no value is present for PlainText, not even an explicit nil
func (o *WikipediaDataPlot) UnsetPlainText() {
	o.PlainText.Unset()
}

// GetHtml returns the Html field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *WikipediaDataPlot) GetHtml() string {
	if o == nil || o.Html.Get() == nil {
		var ret string
		return ret
	}
	return *o.Html.Get()
}

// GetHtmlOk returns a tuple with the Html field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *WikipediaDataPlot) GetHtmlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Html.Get(), o.Html.IsSet()
}

// HasHtml returns a boolean if a field has been set.
func (o *WikipediaDataPlot) HasHtml() bool {
	if o != nil && o.Html.IsSet() {
		return true
	}

	return false
}

// SetHtml gets a reference to the given NullableString and assigns it to the Html field.
func (o *WikipediaDataPlot) SetHtml(v string) {
	o.Html.Set(&v)
}
// SetHtmlNil sets the value for Html to be an explicit nil
func (o *WikipediaDataPlot) SetHtmlNil() {
	o.Html.Set(nil)
}

// UnsetHtml ensures that no value is present for Html, not even an explicit nil
func (o *WikipediaDataPlot) UnsetHtml() {
	o.Html.Unset()
}

func (o WikipediaDataPlot) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.PlainText.IsSet() {
		toSerialize["plainText"] = o.PlainText.Get()
	}
	if o.Html.IsSet() {
		toSerialize["html"] = o.Html.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableWikipediaDataPlot struct {
	value *WikipediaDataPlot
	isSet bool
}

func (v NullableWikipediaDataPlot) Get() *WikipediaDataPlot {
	return v.value
}

func (v *NullableWikipediaDataPlot) Set(val *WikipediaDataPlot) {
	v.value = val
	v.isSet = true
}

func (v NullableWikipediaDataPlot) IsSet() bool {
	return v.isSet
}

func (v *NullableWikipediaDataPlot) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWikipediaDataPlot(val *WikipediaDataPlot) *NullableWikipediaDataPlot {
	return &NullableWikipediaDataPlot{value: val, isSet: true}
}

func (v NullableWikipediaDataPlot) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWikipediaDataPlot) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


