/*
IMDb-API

The IMDb-API Documentation. You need a <a href='/Identity/Account/Manage' target='_blank'><code>API Key</code></a> for testing APIs.<br/><a class='link' href='/API'>Back to API Tester</a>

API version: 1.8.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package client

import (
	"encoding/json"
)

// UserRatingDataDetail struct for UserRatingDataDetail
type UserRatingDataDetail struct {
	Rating NullableString `json:"rating,omitempty"`
	Percent NullableString `json:"percent,omitempty"`
	Votes NullableString `json:"votes,omitempty"`
}

// NewUserRatingDataDetail instantiates a new UserRatingDataDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserRatingDataDetail() *UserRatingDataDetail {
	this := UserRatingDataDetail{}
	return &this
}

// NewUserRatingDataDetailWithDefaults instantiates a new UserRatingDataDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserRatingDataDetailWithDefaults() *UserRatingDataDetail {
	this := UserRatingDataDetail{}
	return &this
}

// GetRating returns the Rating field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserRatingDataDetail) GetRating() string {
	if o == nil || o.Rating.Get() == nil {
		var ret string
		return ret
	}
	return *o.Rating.Get()
}

// GetRatingOk returns a tuple with the Rating field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserRatingDataDetail) GetRatingOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Rating.Get(), o.Rating.IsSet()
}

// HasRating returns a boolean if a field has been set.
func (o *UserRatingDataDetail) HasRating() bool {
	if o != nil && o.Rating.IsSet() {
		return true
	}

	return false
}

// SetRating gets a reference to the given NullableString and assigns it to the Rating field.
func (o *UserRatingDataDetail) SetRating(v string) {
	o.Rating.Set(&v)
}
// SetRatingNil sets the value for Rating to be an explicit nil
func (o *UserRatingDataDetail) SetRatingNil() {
	o.Rating.Set(nil)
}

// UnsetRating ensures that no value is present for Rating, not even an explicit nil
func (o *UserRatingDataDetail) UnsetRating() {
	o.Rating.Unset()
}

// GetPercent returns the Percent field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserRatingDataDetail) GetPercent() string {
	if o == nil || o.Percent.Get() == nil {
		var ret string
		return ret
	}
	return *o.Percent.Get()
}

// GetPercentOk returns a tuple with the Percent field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserRatingDataDetail) GetPercentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Percent.Get(), o.Percent.IsSet()
}

// HasPercent returns a boolean if a field has been set.
func (o *UserRatingDataDetail) HasPercent() bool {
	if o != nil && o.Percent.IsSet() {
		return true
	}

	return false
}

// SetPercent gets a reference to the given NullableString and assigns it to the Percent field.
func (o *UserRatingDataDetail) SetPercent(v string) {
	o.Percent.Set(&v)
}
// SetPercentNil sets the value for Percent to be an explicit nil
func (o *UserRatingDataDetail) SetPercentNil() {
	o.Percent.Set(nil)
}

// UnsetPercent ensures that no value is present for Percent, not even an explicit nil
func (o *UserRatingDataDetail) UnsetPercent() {
	o.Percent.Unset()
}

// GetVotes returns the Votes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UserRatingDataDetail) GetVotes() string {
	if o == nil || o.Votes.Get() == nil {
		var ret string
		return ret
	}
	return *o.Votes.Get()
}

// GetVotesOk returns a tuple with the Votes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UserRatingDataDetail) GetVotesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Votes.Get(), o.Votes.IsSet()
}

// HasVotes returns a boolean if a field has been set.
func (o *UserRatingDataDetail) HasVotes() bool {
	if o != nil && o.Votes.IsSet() {
		return true
	}

	return false
}

// SetVotes gets a reference to the given NullableString and assigns it to the Votes field.
func (o *UserRatingDataDetail) SetVotes(v string) {
	o.Votes.Set(&v)
}
// SetVotesNil sets the value for Votes to be an explicit nil
func (o *UserRatingDataDetail) SetVotesNil() {
	o.Votes.Set(nil)
}

// UnsetVotes ensures that no value is present for Votes, not even an explicit nil
func (o *UserRatingDataDetail) UnsetVotes() {
	o.Votes.Unset()
}

func (o UserRatingDataDetail) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Rating.IsSet() {
		toSerialize["rating"] = o.Rating.Get()
	}
	if o.Percent.IsSet() {
		toSerialize["percent"] = o.Percent.Get()
	}
	if o.Votes.IsSet() {
		toSerialize["votes"] = o.Votes.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableUserRatingDataDetail struct {
	value *UserRatingDataDetail
	isSet bool
}

func (v NullableUserRatingDataDetail) Get() *UserRatingDataDetail {
	return v.value
}

func (v *NullableUserRatingDataDetail) Set(val *UserRatingDataDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableUserRatingDataDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableUserRatingDataDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserRatingDataDetail(val *UserRatingDataDetail) *NullableUserRatingDataDetail {
	return &NullableUserRatingDataDetail{value: val, isSet: true}
}

func (v NullableUserRatingDataDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserRatingDataDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


